/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Creditos.java
 *
 * Created on 12-nov-2010, 0:54:43
 */

package proyectoiii_200925287;

/**
 *
 * @author Administrador
 */
public class Creditos extends javax.swing.JFrame {

    /** Creates new form Creditos */
    public Creditos() {
        initComponents();
        this.setBounds(350,200,400,300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Israel Alexander Grajeda Rodriguez");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 260, 250, 20);

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Java Battle Craft");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 20, 190, 26);

        jLabel4.setFont(new java.awt.Font("BankGothic Lt BT", 0, 10));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Guatemala 12/11/2010");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 0, 140, 20);

        jLabel5.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("III Proyecto Laboratorio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 100, 170, 20);

        jLabel6.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ing.: Julio Cesar Escobar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 140, 170, 20);

        jLabel7.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Auxs.: Marco Guevara - Chali Monroy");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 180, 250, 20);

        jLabel8.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("200925287");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 220, 90, 20);

        jLabel9.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IPC 1 D");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 60, 60, 20);

        jLabel10.setFont(new java.awt.Font("BankGothic Lt BT", 0, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("IDE: NetBeans 6.9");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 220, 130, 20);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 270, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiii_200925287/autobots-decepticons-logos.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
